name: gotest
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.17.x, 1.19.x]
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/checkout@v3
    - run: go version
    - run: go build main
    - run: go run main.go